name: Cucumber Hybrid Framework

on:
  push:
    branches:
      - main      
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # runs on Linux, Windows, Mac

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Java (JDK 17, adjust if needed)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Check the target folder for report and if doesn't have then create it automatically
      - name: Ensure Cucumber report folder exists
        run: mkdir -p target/cucumber-reports/html

      # Step 4: Build project and run tests using Maven
      - name: Build and Run Tests
        run: mvn clean test

      # Step 4: Upload Cucumber JSON reports as artifact
      - name: Upload Cucumber JSON Reports
        uses: actions/upload-artifact@v6
        with:
          name: cucumber-json
          path: target/cucumber-reports/cucumber.json

      # Step 5: Upload Cucumber HTML reports as artifact
      - name: Upload Cucumber HTML Reports
        uses: actions/upload-artifact@v6
        with:
          name: cucumber-html
          path: target/cucumber-reports/html




